---
- name: Ensure dependencies are installed.
  apt: pkg=curl state=installed

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_pkg_version }}_all.deb"
    checksum: "{{ jenkins_pkg_checksum }}"
    dest: /var/cache/apt/archives/jenkins_{{ jenkins_pkg_version }}_all.deb
  when: jenkins_pkg_version is defined

- name: Check that jenkins package is downloaded
  stat:
    path: /var/cache/apt/archives/jenkins_{{ jenkins_pkg_version }}_all.deb
  register: specific_version

- name: Check that correct version of Jenkins is installed.
  apt:
    deb: /var/cache/apt/archives/jenkins_{{ jenkins_pkg_version }}_all.deb
    state: installed
  when: specific_version.stat.exists

- name: Ensure Jenkins is installed.
  apt: name=jenkins state=installed
  when: jenkins_pkg_version is undefined
