---
- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
    state: installed

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes
  when: jenkins_repo_url != ''

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  when: jenkins_version is defined

- name: Check if we downloaded a specific version of Jenkins.
  stat:
    path: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  register: specific_version
  when: jenkins_version is defined

- name: Install our specific version of Jenkins.
  apt:
    deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
    state: installed
  when: jenkins_version is defined and specific_version.stat.exists
  notify: configure default users

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_pkg_version }}_all.deb"
    checksum: "{{ jenkins_pkg_checksum }}"
    dest: /var/cache/apt/archives/jenkins_{{ jenkins_pkg_version }}_all.deb
  when: jenkins_pkg_version is defined

- name: Check that jenkins package is downloaded
  stat:
    path: /var/cache/apt/archives/jenkins_{{ jenkins_pkg_version }}_all.deb
  register: specific_version

- name: Check that correct version of Jenkins is installed.
  apt:
    deb: /var/cache/apt/archives/jenkins_{{ jenkins_pkg_version }}_all.deb
    state: installed
  when: specific_version.stat.exists

- name: Ensure Jenkins is installed.
  apt:
    name: jenkins
    state: "{{ jenkins_package_state }}"
  notify: configure default users
